apiVersion: v1
kind: Service
metadata:
  name: {{ template "tidb.fullname" . }}
  labels:
    app: {{ template "tidb.name" . }}
    chart: {{ template "tidb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.serverPort }}
      name: tidb-server
    - port: {{ .Values.statusPort }}
      name: tidb-status
  selector:
    app: {{ template "tidb.name" . }}
    release: {{ .Release.Name }}
